Repository AY2324S1-CS2103T-T10-2/tp, pull requests merged in 2023-10, with the labels that each got.

#55 docs: Update DG to reflect user stories and use cases
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#61 docs: Update Ui image
  docs/images/Ui.png
Labels: priority.High, type.Documentation

#62 Update UG for v1.1
  docs/DraftUserGuide.md
  docs/images/error/deleteTask_error.png
  docs/images/error/deleteTask_error1.png
  docs/images/error/editTask_error.png
  docs/images/helpMessage.png
  docs/images/output/deleteTask_success.png
  docs/images/output/deleteTask_success1.png
  docs/images/output/editTask_success1.png
  docs/images/output/editTask_success2.png
  docs/images/output/help_success.png
Labels: priority.High, type.Documentation

#47 fix: Attempt to fix broken paths on GitHub Pages
  docs/_includes/admonition.html
  docs/_sass/admonition.scss
  docs/assets/css/style.scss
Labels: type.Bug, priority.High, severity.VeryLow

#56 docs: Update DG NFRs and Use cases
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#63 docs: Update DG for v1.1
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#59 docs: Update UG for deletePerson and addTask
  docs/DraftUserGuide.md
  docs/images/deletePerson_success.png
  docs/images/error/addTask_error.png
  docs/images/error/deletePerson_error.png
  docs/images/output/addTask_success.png
  docs/images/output/deletePerson_success.png
Labels: priority.High, type.Documentation

#64 docs: Update UG v1.1
  docs/DraftUserGuide.md
  docs/images/error/addPerson_error.png
  docs/images/output/listTask_success.png
Labels: priority.High, type.Documentation

#58 docs: Update user guide
  docs/DraftUserGuide.md
  docs/images/error/editPerson_error.png
  docs/images/error/editPerson_wrongIndex.png
  docs/images/error/markTask_error.png
  docs/images/error/unmarkTask_error.png
  docs/images/output/deleteAllTask_success.png
  docs/images/output/editPerson_success.png
  docs/images/output/markTask_success.png
  docs/images/output/unmarkTask_success.png
Labels: priority.High, type.Documentation

#57 docs: Update DG Use Cases
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#54 docs: Update Developer Guide with user profile and value proposition
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#66 chore: Move changes to UG
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#67 chore: Move changes from draft UG to actual UG
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#68 chore: Update UG with final format from draft UG
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#69 docs: Copy over DraftUG to UG
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#70 docs: Move contents from DraftUserGuide to UserGuide
  docs/DraftUserGuide.md
  docs/UserGuide.md
  docs/images/error/findPerson_error.png
  docs/images/error/findTask_error.png
  docs/images/output/findPerson_noResults.png
  docs/images/output/findPerson_success.png
  docs/images/output/findTask_noResults.png
  docs/images/output/findTask_success.png
Labels: priority.High, type.Documentation

#72 docs: Remove all traces of AB3 in UG
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#75 feat: Update help command
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Story, priority.High

#71 chore: Update icons for CoordiMate
  docs/_includes/custom-head.html
  docs/assets/img/favicon/apple-touch-icon.png
  docs/assets/img/favicon/favicon-16x16.png
  docs/assets/img/favicon/favicon-32x32.png
  docs/assets/img/favicon/favicon.ico
  src/main/resources/images/address_book_32.png
Labels: type.Chore, priority.Medium

#73 feat: Implement addPerson command
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Story, priority.High

#76 refactor: Update editPerson
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Story, priority.High

#77 feat: deleteAllPerson command
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAllPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAllPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: type.Story, priority.High

#81 feat: Add Task Classes
  src/main/java/seedu/address/model/task/Note.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/Title.java
  src/main/java/seedu/address/model/task/exceptions/DuplicateTaskException.java
  src/main/java/seedu/address/model/task/exceptions/TaskNotFoundException.java
  src/test/java/seedu/address/model/task/NoteTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/model/task/TitleTest.java
Labels: type.Story, priority.High

#83 feat: Implement tasks storage
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateTaskAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidTaskAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalTasksAddressBook.json
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/task/UniqueTaskListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Story, priority.High

#84 feat: addTask command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/MessagesTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/testutil/TaskUtil.java
Labels: type.Story, priority.High

#82 feat: Implement listPerson command
  src/main/java/seedu/address/logic/commands/ListPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High

#85 feat: Implement Find Task
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindTaskCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/NoteContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/TaskContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/TitleContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindTaskCommandParserTest.java
  src/test/java/seedu/address/model/task/NoteContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/TaskContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/TitleContainsKeywordsPredicateTest.java
Labels: type.Story, priority.High

#90 feat: Implement delete all task
  src/main/java/seedu/address/logic/commands/DeleteAllTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/test/java/seedu/address/logic/commands/DeleteAllTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/task/UniqueTaskListTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
Labels: type.Story, priority.High

#92 feat: Load and Store Task statuses
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/test/data/ConfigUtilTest/EmptyConfig.json
  src/test/data/ConfigUtilTest/ExtraValuesConfig.json
  src/test/data/ConfigUtilTest/TypicalConfig.json
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateTaskAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidTaskAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalTasksAddressBook.json
  src/test/data/JsonUserPrefsStorageTest/EmptyUserPrefs.json
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Story, priority.High

#94 feat: Add status icons for Task list
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/images/done.png
  src/main/resources/images/not_done.png
  src/main/resources/view/TaskListCard.fxml
Labels: type.Story, priority.High

#96 feat: Update UI for Result Display Box
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Story, priority.High

#101 feat: Add tag to task
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalTasksAddressBook.json
  src/test/java/seedu/address/logic/MessagesTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditTaskDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditTaskCommandParserTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/model/task/UniqueTaskListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Story, priority.High

#107 docs: Update UG
  docs/UserGuide.md
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High, type.Documentation

#109 docs: Update implementation of deleteTask to DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteTaskSequenceDiagram.puml
  docs/images/DeleteTaskSequenceDiagram.png
Labels: priority.High, type.Documentation

#99 feat: Filter task list by task status
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/FindDoneCommand.java
  src/main/java/seedu/address/logic/commands/FindNotDoneCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/java/seedu/address/logic/commands/FindDoneCommandTest.java
  src/test/java/seedu/address/logic/commands/FindNotDoneCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
Labels: type.Story, priority.Medium

#110 chore: Add assertions to build gradle file
  build.gradle
Labels: type.Chore, priority.High

#102 feat: Implement list tags command
  src/main/java/seedu/address/logic/commands/ListTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/TagFrequencyTable.java
  src/test/java/seedu/address/logic/commands/ListTagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/model/tag/TagFrequencyTableTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: type.Story, priority.Medium

#103 feat: Implement findTag
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindTagCommandParser.java
  src/main/java/seedu/address/model/person/PersonContainsTagsPredicate.java
  src/main/java/seedu/address/model/task/TaskContainsTagsPredicate.java
  src/test/java/seedu/address/logic/commands/FindTagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindTagCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonContainsTagsPredicateTest.java
  src/test/java/seedu/address/model/task/TaskContainsTagsPredicateTest.java
Labels: type.Story, priority.Medium

#106 feat: Shorten commands
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAllPersonCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAllTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindDoneCommand.java
  src/main/java/seedu/address/logic/commands/FindNotDoneCommand.java
  src/main/java/seedu/address/logic/commands/FindPersonCommand.java
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
  src/main/java/seedu/address/logic/commands/FindTaskCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListPersonCommand.java
  src/main/java/seedu/address/logic/commands/ListTagCommand.java
  src/main/java/seedu/address/logic/commands/ListTaskCommand.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TaskUtil.java
Labels: type.Story, priority.High

#100 docs: Update v1.3 Developer Guide
  docs/DeveloperGuide.md
  docs/assets/svg/dg/EditTaskSequenceDiagram.svg
  docs/assets/svg/dg/FindTaskSequenceDiagram.svg
  docs/assets/svg/dg/ListTaskSequenceDiagram.svg
  docs/assets/svg/dg/MarkTaskSequenceDiagram.svg
  docs/diagrams/DeleteTaskSequenceDiagram.puml
  docs/diagrams/EditTaskSequenceDiagram.puml
  docs/diagrams/FindTaskSequenceDiagram.puml
  docs/diagrams/ListTaskSequenceDiagram.puml
  docs/diagrams/MarkTaskSequenceDiagram.puml
  docs/images/DeleteTaskSequenceDiagram.png
  docs/images/ListTaskSequenceDiagram.png
Labels: priority.High, type.Documentation
