Repository AY2324S1-CS2103T-T10-2/tp, pull requests merged in 2023-11, with the labels that each got.

#112 feat: Implement listAll command
  src/main/java/seedu/address/logic/commands/ListAllCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/ListAllCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Story, priority.Medium

#117 feat: Implement findAllTag command
  src/main/java/seedu/address/logic/commands/FindAllTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindAllTagCommandParser.java
  src/main/java/seedu/address/model/person/PersonContainsAllTagsPredicate.java
  src/main/java/seedu/address/model/task/TaskContainsAllTagsPredicate.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalTasksAddressBook.json
  src/test/java/seedu/address/logic/commands/FindAllTagCommandTest.java
  src/test/java/seedu/address/logic/commands/FindNotDoneCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindAllTagCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonContainsAllTagsPredicateTest.java
  src/test/java/seedu/address/model/tag/TagFrequencyTableTest.java
  src/test/java/seedu/address/model/task/TaskContainsAllTagsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalAddressBook.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Story, priority.Medium

#120 feat: Add DeleteTagPerson command
  src/main/java/seedu/address/logic/commands/DeleteTagPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagPersonCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteTagPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTagPersonCommandParserTest.java
Labels: type.Story, priority.High

#118 feat: Implement addTagTask and addTagPerson commands
  src/main/java/seedu/address/logic/commands/AddTagPersonCommand.java
  src/main/java/seedu/address/logic/commands/AddTagTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTagPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTagTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/AddTagPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTagTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTagPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddTagTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
Labels: type.Story, priority.High

#115 feat: Add delete all done tasks
  src/main/java/seedu/address/logic/commands/DeleteAllDoneCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/DeleteAllDoneCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/ModelStub.java
Labels: type.Story, priority.Medium

#123 chore: Bump version number to 1.3.0
  src/main/java/seedu/address/MainApp.java
Labels: type.Chore

#121 docs: Update v1.3b Developer Guide
  docs/DeveloperGuide.md
  docs/assets/svg/dg/ArchitectureDiagram.svg
  docs/assets/svg/dg/ArchitectureSequenceDiagram.svg
  docs/assets/svg/dg/BetterModelClassDiagram.svg
  docs/assets/svg/dg/CommitActivityDiagram.svg
  docs/assets/svg/dg/ComponentManagers.svg
  docs/assets/svg/dg/DeleteTaskSequenceDiagram.svg
  docs/assets/svg/dg/LogicClassDiagram.svg
  docs/assets/svg/dg/ModelClassDiagram.svg
  docs/assets/svg/dg/ParserClasses.svg
  docs/assets/svg/dg/StorageClassDiagram.svg
  docs/assets/svg/dg/UiClassDiagram.svg
  docs/assets/svg/dg/UndoRedoState0.svg
  docs/assets/svg/dg/UndoRedoState1.svg
  docs/assets/svg/dg/UndoRedoState2.svg
  docs/assets/svg/dg/UndoRedoState3.svg
  docs/assets/svg/dg/UndoRedoState4.svg
  docs/assets/svg/dg/UndoRedoState5.svg
  docs/assets/svg/dg/UndoSequenceDiagram.svg
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/ComponentManagers.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/DeleteTaskSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
Labels: priority.High, type.Documentation

#165 docs: Update app version in logs
  src/main/java/seedu/address/MainApp.java
Labels: type.Chore, priority.Medium

#158 docs: Update Megan's PPP
  docs/team/m1oojv.md
Labels: priority.High, type.Documentation

#157 docs: Update Pranavi's PPP
  docs/team/pra-navi.md
Labels: priority.High, type.Documentation

#166 docs: Update Lingxi's PPP
  docs/team/hugenoob.md
Labels: priority.High, type.Documentation

#162 docs: Update Alan's PPP
  docs/team/freshcabbage123.md
Labels: priority.High, type.Documentation

#156 docs: Update Jiakai's PPP Page
  docs/team/jiakai-17.md
Labels: priority.High, type.Documentation

#167 refactor: Fix javadocs and improve code quality
  src/main/java/seedu/address/logic/commands/DeleteTagPersonCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagTaskCommand.java
Labels: priority.High, type.Documentation

#175 docs: Update repo README
  README.md
Labels: priority.Medium, type.Documentation

#177 docs: Update AboutUs
  docs/AboutUs.md
Labels: priority.Medium, type.Documentation

#168 docs: Reformat PPP to fit page limit at default zoom level
  docs/team/jiakai-17.md
Labels: priority.High, type.Documentation

#170 docs: Cut PPP length
  docs/team/hugenoob.md
Labels: priority.High, type.Documentation

#171 fix: Remove page break in PPP
  docs/team/pra-navi.md
Labels: priority.High, type.Documentation

#169 docs: Reformat Alan's PPP
  docs/team/freshcabbage123.md
Labels: priority.High, type.Documentation

#176 docs: Reformat Megan PPP
  docs/team/m1oojv.md
Labels: priority.High, type.Documentation

#174 docs: Update Developer Guide for v1.4 release
  docs/DeveloperGuide.md
  docs/assets/svg/dg/LogicClassDiagram.svg
  docs/assets/svg/dg/SDCreateFindTaskCommandResult.svg
  docs/assets/svg/dg/SDCreateTaskPredicate.svg
  docs/assets/svg/dg/UiClassDiagram.svg
  docs/diagrams/SDCreateFindTaskCommandResult.puml
  docs/diagrams/SDCreateTaskPredicate.puml
Labels: priority.High, type.Documentation

#172 docs: Update User Guide for v1.4 release
  docs/UserGuide.md
  docs/_sass/minima/_layout.scss
  docs/assets/css/style.scss
  docs/images/output/addPerson_success.png
  docs/images/output/findAllTag_success.png
  docs/images/output/findTag_success.png
  docs/images/output/listPerson_success.png
  docs/images/output/listTask_success.png
Labels: priority.High, type.Documentation

#178 docs: Remove line break
  docs/team/pra-navi.md
Labels: priority.High, severity.High
